### ISSUE TITLE
Modules not loaded

### ISSUE THREAD

**Issue by synatree** [mharsch/node-pi-plates#1]
Something is happening with the invocation of Python; the piplates module is not found (yes, it is installed).

**Comment by mharsch** [comment]
we need to launch the python helper script using 'python3' instead of 'python'

**Comment by synatree** [comment]
https://github.com/mharsch/node-pi-plates/compare/master...synatree:master

You can compare my changes with yours; these were made to make my situation work, but in general I implemented a file lock on the DAQC and Relay parts so that they could be used simultaneously from several processes, and so that a global number of relays that were allowed to be on at any time could be enforced.  This is important in real life because relays use a lot of power.  I also implemented some async versions of the functions to help me in my situation.  You can certainly take it or leave it :)
